# Generated by Django 4.2.5 on 2023-11-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0187_hop_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateFirewallStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.PositiveIntegerField(db_index=True, default=None, null=True)),
                ('ip_address', models.CharField(max_length=256)),
                (
                    'status',
                    models.CharField(
                        choices=[('waiting', 'waiting'), ('processing', 'processing'), ('installing', 'installing'), ('updated', 'updated')],
                        default='waiting',
                        max_length=24,
                    ),
                ),
            ],
        ),
    ]
