# Generated by Django 4.2.5 on 2023-11-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0188_updatefirewallstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatefirewallstatus',
            name='group_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
