# Generated by Django 4.2.5 on 2023-11-21 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0190_alter_updatefirewallstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatefirewallstatus',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='updatefirewallstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
