# Generated by Django 4.2.5 on 2023-11-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0191_updatefirewallstatus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatefirewallstatus',
            name='sequence',
            field=models.BooleanField(default=False),
        ),
    ]
