# Generated by Django 4.2.5 on 2023-11-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0192_updatefirewallstatus_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatefirewallstatus',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
