# Generated by Django 4.2.5 on 2023-12-05 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0194_updatefirewallstatuslogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateFirewallBackupFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.PositiveIntegerField(db_index=True, default=None, null=True)),
                ('ip_address', models.CharField(max_length=256)),
                ('file_name', models.CharField(max_length=250, null=True)),
                ('xml_content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
