# Generated by Django 4.2.5 on 2023-12-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0195_updatefirewallbackupfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatefirewallstatus',
            name='api_key',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='updatefirewallstatus',
            name='current_version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='updatefirewallstatus',
            name='update_version',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
