# Generated by Django 4.2.5 on 2023-12-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0196_updatefirewallstatus_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatefirewallstatus',
            name='status',
            field=models.CharField(
                choices=[
                    ('waiting', 'waiting'),
                    ('solar_wind_mute', 'solar_wind_mute'),
                    ('backup', 'backup'),
                    ('cleanup', 'cleanup'),
                    ('download', 'download'),
                    ('install', 'install'),
                    ('reboot', 'reboot'),
                    ('login', 'login'),
                    ('solar_wind_unmute', 'solar_wind_unmute'),
                    ('updated', 'updated'),
                ],
                default='waiting',
                max_length=24,
            ),
        ),
    ]
